services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace
    command: sleep infinity
    depends_on: [postgres]
  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: holo
      POSTGRES_USER: holocleanuser
      POSTGRES_PASSWORD: abcd1234
    ports: ["5432:5432"]
